version: '2'
services:
    redis:
        image: redis:alpine

    websocket:
        image: offlinegmbh/socketio
        depends_on:
            - redis
        links:
            - redis
        volumes:
            - ./socket.js:/srv/socket.js
            - ./docker-runtime/websocket:/srv/logs
        ports:
            - "3000:3000"
